from collections.abc import Iterable


def is_acceptable(target, white_list=None, black_list=None):
    white_list = white_list if white_list is not None else set()
    black_list = black_list if black_list is not None else set()

    assert isinstance(white_list, Iterable)
    assert isinstance(black_list, Iterable)

    return True if not (black_list and target in black_list) and (not white_list or target in white_list) else False


def filter_acceptable(targets, white_list=None, black_list=None, key=lambda x: x):
    white_list = white_list if white_list is not None else set()
    black_list = black_list if black_list is not None else set()

    assert isinstance(white_list, Iterable)
    assert isinstance(black_list, Iterable)

    white_list = set(white_list)
    black_list = set(black_list)

    def _filter_by_white_list(instances):
        if white_list:
            return filter(lambda x: key(x) in white_list, instances)
        else:
            return instances

    def _filter_by_black_list(instances):
        if black_list:
            instances = filter(lambda x: key(x) not in black_list, targets)
        else:
            pass

        return _filter_by_white_list(instances)

    return _filter_by_black_list(targets)


if __name__ == '__main__':
    names = ['Alisha Reyes', 'Michael Clark', 'Selena Schneider', 'Austin Pierce', 'Michael Andrews', 'Rachel Allen',
             'Cheryl Bowers', 'Donald Snyder', 'Alicia Clark', 'Kyle Moore', 'Deborah Zimmerman', 'Jeffrey Simon',
             'Sarah Hall', 'Cheryl Aguirre', 'Shannon Sullivan', 'Emily Brewer', 'Keith Martin', 'Tiffany Carroll',
             'Mark Clark', 'Julie Nunez', 'Brenda Hunt', 'Christian Obrien', 'Heather Haley', 'Kimberly Cruz',
             'Krista Garcia', 'Maria Copeland', 'Tammy Holder', 'Cynthia Stevens', 'Christina Williams', 'Paul Garner',
             'James Byrd', 'Carrie Garcia', 'Melissa Lopez', 'Ellen Phillips', 'Michael Jackson', 'Corey Banks',
             'Andrea Moses', 'Jeffrey Carter', 'Mark King', 'Stephen Barr', 'Samuel Johnston', 'Harold Chung',
             'Anthony Romero', 'Shane Torres', 'Michael Diaz', 'Greg Carroll', 'Travis Taylor', 'David Moreno',
             'Mario Taylor', 'Jeremy Carpenter', 'Tracy Russell', ]  # generated by Faker fake.name()

    bad_guys = ['Cheryl Aguirre', 'Shannon Sullivan', 'Emily Brewer']
    assert is_acceptable('Selena Schneider', black_list=bad_guys) is True
    assert is_acceptable('Shannon Sullivan', black_list=bad_guys) is False

    results = list(filter_acceptable(names, white_list=['Clark', 'Taylor'], key=lambda name: name.split()[-1]))
    assert results == ['Michael Clark', 'Alicia Clark', 'Mark Clark', 'Travis Taylor', 'Mario Taylor']
